import "./globals.css";
import "../css/style.css";
import "bootstrap/dist/css/bootstrap.min.css";


export const metadata = {
  title: "Forum FrameWorks",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <head>
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css"/>
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
      </head>
      <body >{children}</body>
    </html>
  );
}